# Site settings
title: Gustavo Vinícius
email: me@gustavovinicius.com
baseurl: ""
url: "http://gustavovinicius.com"
username: gustavovnicius
usernametwitter: "@gustavovncius"
usernamekeybase: gustavo

# Build settings
markdown: kramdown
permalink: pretty
